maven_server(
    name = "default",
    url = "http://central.maven.org/maven2/",
)

maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    sha1 = "cce0823396aa693798f8882e64213b1772032b09",
)

maven_jar(
    name = "org_hamcrest_hamcrest_library",
    artifact = "org.hamcrest:hamcrest-library:1.3",
    sha1 = "4785a3c21320980282f9f33d0d1264a69040538f",
)

maven_jar(
    name = "org_springframework_boot_spring_boot_autoconfigure",
    artifact = "org.springframework.boot:spring-boot-autoconfigure:2.1.3.RELEASE",
    sha1 = "58e07f69638a3ca13dffe8a2b68d284af376d105",
)

maven_jar(
    name = "org_springframework_boot_spring_boot_test_autoconfigure",
    artifact = "org.springframework.boot:spring-boot-test-autoconfigure:2.1.3.RELEASE",
    sha1 = "f667520b788e87a38bcee2538fce16d3d1a484a5",
)

maven_jar(
    name = "org_springframework_boot_spring_boot_test",
    artifact = "org.springframework.boot:spring-boot-test:2.1.3.RELEASE",
    sha1 = "3615e9ac8c032ff246d6f30fe36642333e45881d",
)

maven_jar(
    name = "org_springframework_boot_spring_boot",
    artifact = "org.springframework.boot:spring-boot:2.1.3.RELEASE",
    sha1 = "92bb92cd73212cefc1e5112e3bbf1f31c154c3fd",
)

maven_jar(
    name = "org_springframework_boot_spring_boot_starter_web",
    artifact = "org.springframework.boot:spring-boot-starter-web:2.1.3.RELEASE",
    sha1 = "e65a0538c3075a0910e7273a9dbedb189761b1ae",
)

maven_jar(
    name = "org_springframework_spring_beans",
    artifact = "org.springframework:spring-beans:5.1.5.RELEASE",
    sha1 = "58b10c61f6bf2362909d884813c4049b657735f5",
)

maven_jar(
    name = "org_springframework_spring_context",
    artifact = "org.springframework:spring-context:5.1.5.RELEASE",
    sha1 = "d39299241a2c8353d83f0f0c84d3677973da7c57",
)

maven_jar(
    name = "org_springframework_spring_test",
    artifact = "org.springframework:spring-test:5.1.5.RELEASE",
    sha1 = "0693fac3c64b4617b7c2b207e45e93529f6594bd",
)

maven_jar(
    name = "org_springframework_spring_web",
    artifact = "org.springframework:spring-web:5.1.5.RELEASE",
    sha1 = "c37c4363be4ad6c5f67e3f9f020497e2d599e325",
)
